import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "var(--surface-canvas)",
        surface: "rgb(var(--surface-rgb) / <alpha-value>)",
        "surface-raised": "rgb(var(--surface-raised-rgb) / <alpha-value>)",
        "surface-inset": "rgb(var(--surface-inset-rgb) / <alpha-value>)",
        card: "rgb(var(--card-rgb) / <alpha-value>)",
        overlay: "var(--surface-overlay)",
        t1: "rgb(var(--text-1-rgb) / <alpha-value>)",
        t2: "rgb(var(--text-2-rgb) / <alpha-value>)",
        t3: "rgb(var(--text-3-rgb) / <alpha-value>)",
        t4: "rgb(var(--text-4-rgb) / <alpha-value>)",
        accent: "rgb(var(--accent-rgb) / <alpha-value>)",
        "accent-hover": "var(--accent-hover)",
        "accent-press": "var(--accent-press)",
        "on-accent": "var(--on-accent)",
        verified: "rgb(var(--verified-rgb) / <alpha-value>)",
        success: "rgb(var(--success-rgb) / <alpha-value>)",
        warning: "rgb(var(--warning-rgb) / <alpha-value>)",
        danger: "rgb(var(--danger-rgb) / <alpha-value>)",
        info: "rgb(var(--info-rgb) / <alpha-value>)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        "accent-subtle": "var(--accent-subtle)",
        "accent-border": "var(--accent-border)",
        "verified-subtle": "var(--verified-subtle)",
        "success-subtle": "var(--success-subtle)",
        "warning-subtle": "var(--warning-subtle)",
        "danger-subtle": "var(--danger-subtle)",
        "info-subtle": "var(--info-subtle)",
        glass: "var(--glass-bg)",
        violet: "rgb(var(--violet-rgb) / <alpha-value>)",
        "violet-subtle": "var(--violet-100)",
        cyan: "rgb(var(--cyan-rgb) / <alpha-value>)",
        magenta: "rgb(var(--magenta-rgb) / <alpha-value>)",

        bg: "var(--surface-canvas)",
        fg: "var(--text-1)",
        muted: "var(--text-3)",
        "surface-2": "var(--surface-raised)",
        "accent-fg": "var(--on-accent)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        card: "var(--shadow-md), var(--highlight-top)",
        "glow-accent": "var(--glow-accent)",
        "glow-violet": "var(--glow-violet)",
        "glow-card": "var(--glow-card)",
        "glow-prism": "var(--glow-prism)",
      },
      backgroundImage: {
        "gradient-accent": "var(--gradient-accent)",
        "gradient-accent-soft": "var(--gradient-accent-soft)",
        subtle: "var(--gradient-subtle)",
      },
    },
  },
  plugins: [],
};

export default config;
